### ISSUE TITLE
feat: use "explain query plan" instead of "explain"

### ISSUE THREAD

**Issue by SamHames** [gvwilson/sql-tutorial#10]
The `explain` command example gives low level details of the SQLite virtual machine which probably isn't intelligible to many people. 

More useful is the `explain query plan` version which shows which indices and what kind of processing is taking place for a given query. This is useful to identify missing indexes and avoid full table scans.

```sql
explain query plan
select
    species,
    avg(body_mass_g)
from penguins
group by species;
```

Output:
```
QUERY PLAN
|--SCAN penguins
`--USE TEMP B-TREE FOR GROUP BY
```

**Comment by gvwilson** [comment]
thanks very much!
