### ISSUE TITLE
feat: explain .command data import from CSV

### ISSUE THREAD

**Issue by APHawkes** [gvwilson/sql-tutorial#22]
While python is a great tool for interacting with sqlite, direct import of data using the .mode csv and .import commands can be useful.

**Comment by gvwilson** [comment]
thanks, I'll add a note - if you'd like to be added to the acknowledgments, can you please let me know your name (either here or by email to gvwilson@third-bit.com)?

**Comment by APHawkes** [comment]
It would be an honor to be acknowledged in this work. I can be addressed as "Adam Hawkes". Thank you for your consideration of my suggestion.
