### ISSUE TITLE
count distinct

### ISSUE THREAD

**Issue by Hasnabruzzn** [gvwilson/sql-tutorial#26]
I would add count (distinct...) to 019: counting

```
select count(*) as count_star, count(sex) as count_specific, count(distinct sex) as count_sexes
from penguins;
```
```
| count_star | count_specific |count_sexes
|------------|----------------|------------|
| 344        | 333            | 2           |
```

- count(*) counts rows
- count(column) counts non-null entries in column
- count(distinct column) counts distinct non-null entries in column (can also be an expression)

Edit: Maybe count_sexes is not the best example...

**Comment by Hasnabruzzn** [comment]
From a technical point of view it's fine. Maybe I'm just overreacting to some 'political' confusions.

Am 6. Februar 2024 15:15:08 MEZ schrieb Greg Wilson ***@***.***>:

**Comment by gvwilson** [comment]
thanks for the suggestion - if you could send me your name (gvwilson@third-bit.com) I'll add you to the acknowledgments
