### ISSUE TITLE
blob section is missing the SELECT query

### ISSUE THREAD

**Issue by simonw** [gvwilson/sql-tutorial#30]
This bit here: https://gvwilson.github.io/sql-tutorial/#blobs

![CleanShot 2024-02-06 at 15 26 17@2x](https://github.com/gvwilson/sql-tutorial/assets/9599/0c932209-3066-4dfc-8d88-f7e23a35abe8)

I think it's missing the `select name, length(content) from images;` query.

**Comment by simonw** [comment]
Or maybe that's deliberate?

https://github.com/gvwilson/sql-tutorial/blob/ace4f26d02467fbd4f043a7116d9fab7757e732b/src/blob.sql#L1-L15

The `-- end` tag comes before that SELECT query.

**Comment by gvwilson** [comment]
It was deliberate - I've omitted quite a few "select whatever to illustrate state of DB" queries from examples to keep things short - but I accept it's confusing. Fix coming.
