### ISSUE TITLE
Interactive code examples

### ISSUE THREAD

**Issue by nalgeon** [gvwilson/sql-tutorial#45]
Hi Greg! Thank you for this great tutorial!

Would you be interested in making the SQL queries in the docs interactive, so that readers can run (and modify) them without leaving the browser? Here is [what it could look like](https://codapi.org/try/sql100/).

If you're interested, I'll be happy to send you a PR.

**Comment by gvwilson** [comment]
Hi Anton - thanks for the suggestion. We're still sorting out the content, which I'm pretty sure will change dramatically when we teach this for the first couple of times to actual people (which I hope will happen in March), but if you'd like to clone the content and create something interactive, it's all open license - just link back to us as the original source. Thanks - Greg

**Comment by nalgeon** [comment]
The thing is, I'd prefer _not_ to clone it. Why make a duplicate interactive version, when we can make the original interactive? But it's your call, of course.
