### ISSUE TITLE
question: one page or many?

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/sql-tutorial#49]
- The first version of this tutorial had all of the material on one long page.
  - Except for the material on Python and PostgreSQL, which was on separates pages.
- This version divides the main material between 12 pages.
  - Pro: topic structure is easier to see
  - Con: 3 of the 9 pages (SQL Tools, More Tools, and Odds and Ends) are miscellaneous topics thrown together
- Please add a comment below to tell me whether you prefer one long page or multiple pages.

**Comment by yabellini** [comment]
I prefer one long page because I can search for what I'm looking for in one place.

**Comment by simonw** [comment]
Is "both" a useful suggestion?

A single page is easier to dump into a tool like Pocket for offline reading, but multiple pages are more useful for things like landing on the right piece of information from a Google search.

So how about defaulting to multiple pages but providing an automatically compiled (and search engine excluded, to avoid duplicate content penalties) single page version for people who want to grab an offline or single-searchable version?

**Comment by hcooney** [comment]
Many pages makes it easy for someone with some knowledge to orient themselves and skip introductory material.

**Comment by aflip** [comment]
Multiple pages, but with a persistent table of contents. eg [Biostats for biomedical research](https://hbiostat.org/bbr/) So it is easy to 1. search the whole book/resource from one page 2. Skip and travel easily to the pages that one needs at that moment 3. review is easier because I can pick what I want to review and just go to that page. A smiliar structure is also seen in [SQL Bolt](https://sqlbolt.com/), which is what I ( a medical scientist)  used to learn SQL

**Comment by defuneste** [comment]
I prefer the new version with multiples pages and less scrolling down.

I would also use an offline single page version. I assume for that I can also fork/clone the repo and build it for that specific need so in my mind it take lower "priority" that "good web version".

**Comment by gvwilson** [comment]
thank you all for your feedback - I've consolidated the lesson into three pages (core, tools, and advanced) which I hope you'll find a good balance. @simonw I'll see if there's an easy way to get both multi-page and single-page versions out of the same source without hacking [Ark](https://www.dmulholl.com/docs/ark/main/) too much - thank you for the suggestion.
